### ISSUE TITLE
A thought on manifests for large plain-text files in magenc

### ISSUE THREAD

**Issue by DougC** [WebOfTrustInfo/rwot7-toronto#111]
Perhaps raising an issue on this isn't the best approach, but I'm not sure where else to discuss this. 

I was thinking that a small change to the way manifest files are handled would eliminate the problem that they can be larger than the 32k block size. From my reading of the spec, manifest files point to simple unstructured chunks of bytes. If, instead, they recursively pointed to s-expression encoded files (i.e. further `raw` or `manifest`) files then for very large plain-text files you would end up with a deeper tree of chunks with manifests as the branches and raw files as the leaves.

https://github.com/WebOfTrustInfo/rwot7-toronto/blob/master/topics-and-advance-readings/magenc.md @cwebber

**Comment by ChristopherA** [comment]
It is fine to use the GitHub issues for comments like these, but it helps if you tell us which specific file are you commenting on, and include the GitHub @ name of the person(s) that submitted the file.

**Comment by DougC** [comment]
Good point. I hadn't appreciated the extent of the repo :-)

**Comment by DougC** [comment]
@cwebber So, reading the spec more carefully I realise this is what you meant when you talked about merkel trees vs. the flat manifest files, so you've already considered this and I'm going to close this issue.
