### ISSUE TITLE
Addressing Global/Local Barriers to Adoption of Decentralized Identity Systems

### ISSUE THREAD

**Issue by itsericbrown** [WebOfTrustInfo/rwot7-toronto#49]
# Addressing Global/Local Barriers to Adoption of Decentralized Identity Systems
Eric Brown — itsericbrown@gmail.com // Cultu.re – https://cultu.re/

## Introduction
Decentralized identity protocols have the potential to overhaul the way we understand and interact with sovereign individuals on a micro and macro level. 

With a technical infrastructure set to have such a profound impact on networks, culture, and governance, how can we ensure that the standards are openly adopted, widely integrated, and effectively embraced? 

This includes individual user adoption, community implementations, and vast social, national, and global recognition and adoption of the standards. It contains communication, marketing, and community questions.

Here, we explore considerations for and barriers to adoption of decentralized identity systems.

## Major Considerations
1. Awareness and Adoption
2. Community Engagement
3. Interoperability
4. Interaction Layers

### Awareness and Adoption
All standards must build initial momentum to reach a critical threshold of adoption. Decentralized identity systems present a fundamental shift away from the existing infrastructure, a paradigm shift in thinking through identity, individuals, and collective organization. 

This presents a problem on two fronts: building awareness of the value of this technology, and also facilitating adoption of the technology into everyday interactions. The later is likely more difficult, as it will require behaviour modification and new ways of thinking for users and organizations.

We must address questions such as:
- How do you convey the value of this system to an individual user?
- How do you convey the value of this to organizations, societies, and nation states that have relied, relatively successfully, on centralized structured and fragmented identity silos?
- How do you get a society to embrace fundamental change?

An idea, no matter how glorious, will fall short of its goal if it is unable to reach adoption from the majority, and to integrate seamlessly and alleviate pains of the dominant, pre-existing model.

### Community Engagement
The resiliency and long-term success of decentralized identity systems will come from the community that stewards it, the community that embraces it, and the community that builds it. 

Open sources models have proven time and time again their ability to affect change and to improve existing systems. This happened _because_ of a the community.

As the system evolves, incentive structures, moderation, review, audit, and development systems must be in place to maintain the integrity and innovation inherent to the systems.

Looking forward, we will need to address:
- How do you attract and incentivize the appropriate talent, decision makers, and movement creators?
- What components contribute to resilient, anti-fragile systems?
- How do you distill wisdom from core contributors to the outer edges to increase participation and complete understanding of a complex, evolving system?

### Interoperability
The freedom of choice of the individual and of the collective is paramount for the future success of governance and individual sovereignty. Individuals must be free to choose and act on these decisions. As a result, the technological underpinnings of the systems must be interoperable, or said differently, technologically agnostic.

It must not prefer, nor force, individuals into a particular modality, technology, or identity/governance model. This level of flexibility is necessary for the adoption and growth of the standards/systems.

There are more technical questions to address on the topic of interoperability:
- Can the standards are systems be, or eventually become, technology and blockchain agnostic?
- How can we build bridges from the existing infrastructure into the new systems, facilitating ease of adoption and reducing friction?
- Is the technology accessible to all members of the community?

### Interaction Layers
A particularly interesting barrier to adoption is the interaction layer, the gateway from everyday accessibility to the underlying infrastructure.

Regardless of the technical level of the technological underpinnings, the interaction layers must be approachable, intuitive, and fluid to fit any implementation size.

There are many examples of projects thinking through these interaction layers, one example being [Sovrin](https://sovrin.org/). There is also [Cultu.re](https://cultu.re/), working to facilitate the integration and adoption of the web of trust standards. 

The interaction layers act as the bow, tying together the gift of decentralized identity and presenting it to the commons. They bring the aforementioned considerations (awareness, community, interoperability) together in a Gestalt that allows for deep engagement and lasting resiliency. 

Given the importance here, there are a few considerations we must consider:
- What is the core offering that must be presented in a UX to the user?
- How do you facilitate change through usability?
- Can design thinking change the world? How can it contribute to this?
- How can a system, designed for the individual, contribute to the collective?
- What is the role of the technological infrastructure in facilitating development of the interaction layer?

## Closing Thoughts
Decentralized identity systems are well poised to fundamentally alter our digital, physical, social, and global interactions. It is nothing short of a re-imagining of what identity means. 

As a result, we need to re-imagine the full spectrum of its presentation, from stewarding the community, to presenting it to the world. Each stage of this process fuels the next, and in order to grow the technology and allow for adoption, we have a lot of questions to be answered.

If you have any thoughts or answers to these questions, please [send them over](mailto:itsericbrown@gmail.com). If you’d like, we’d love to hear what you think over at [Cultu.re](https://t.me/cultureisfuture).

**Comment by ChristopherA** [comment]
@ShannonA added this to topics at https://github.com/WebOfTrustInfo/rwot7/blob/master/topics-and-advance-readings/Adoption.md
